"""Export scenarios into SQL for the mock ERP PostgreSQL source."""

from __future__ import annotations

from datetime import date
from decimal import Decimal

from data_source.mock_data_factory.models import BusinessScenarioSet


def sql_string(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_date(value: date) -> str:
    return f"DATE {sql_string(value.isoformat())}"


def sql_numeric(value: Decimal | int | None) -> str:
    if value is None:
        return "NULL"
    return str(value)


def render_mock_erp_pg_sql(scenario_set: BusinessScenarioSet) -> str:
    lines = [
        "-- Generated by data_source.mock_data_factory.",
        f"-- Scenario set: {scenario_set.name}",
        "",
        "DO $$",
        "DECLARE",
        "    v_order_id INTEGER;",
        "    v_invoice_id INTEGER;",
        "BEGIN",
    ]

    for order in scenario_set.sales_orders:
        lines.extend(
            [
                f"    -- Scenario: {order.name}",
                "    v_order_id := erp_sales.create_sales_order("
                f"{order.customer_id}, {order.channel_id}, {order.branch_id}, {sql_date(order.order_date)});",
            ]
        )

        for order_line in order.lines:
            lines.append(
                "    PERFORM erp_sales.add_sales_order_line("
                f"v_order_id, {order_line.product_id}, {order_line.warehouse_id}, "
                f"{sql_numeric(order_line.quantity)}, {sql_numeric(order_line.unit_price)}, "
                f"{sql_numeric(order_line.discount_amount)}, {sql_numeric(order_line.promotion_id)});"
            )

        lines.append("    PERFORM erp_sales.confirm_order(v_order_id);")

        if order.fulfillment_date is not None:
            lines.append(
                "    PERFORM erp_sales.fulfill_order("
                f"v_order_id, {sql_date(order.fulfillment_date)}, {order.carrier_id});"
            )

        if order.invoice_date is not None:
            lines.append(
                "    v_invoice_id := erp_finance.create_invoice_from_order("
                f"v_order_id, {sql_date(order.invoice_date)}, {order.due_days});"
            )

            for payment in order.payments:
                lines.append(
                    "    PERFORM erp_finance.record_payment("
                    f"v_invoice_id, {sql_numeric(payment.amount)}, {sql_string(payment.method)}, "
                    f"{sql_date(payment.payment_date)});"
                )

        lines.append("")

    lines.extend(["END;", "$$;", ""])
    return "\n".join(lines)
