services:
  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=${ODOO_DB_USER:?ODOO_DB_USER is required}
      - PASSWORD=${ODOO_DB_PASSWORD:?ODOO_DB_PASSWORD is required}
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${ODOO_DB_NAME:-postgres}
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:?ODOO_DB_PASSWORD is required}
      - POSTGRES_USER=${ODOO_DB_USER:?ODOO_DB_USER is required}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

volumes:
  odoo-web-data:
    name: end-to-end-dataflatform_odoo-web-data
  odoo-db-data:
    name: end-to-end-dataflatform_odoo-db-data
