CREATE SCHEMA IF NOT EXISTS erp_core;
CREATE SCHEMA IF NOT EXISTS erp_inventory;
CREATE SCHEMA IF NOT EXISTS erp_sales;
CREATE SCHEMA IF NOT EXISTS erp_logistics;
CREATE SCHEMA IF NOT EXISTS erp_finance;
