CREATE TABLE erp_core.companies (
    company_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_code TEXT NOT NULL UNIQUE,
    company_name TEXT NOT NULL,
    country TEXT NOT NULL,
    currency TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE erp_core.branches (
    branch_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL,
    branch_code TEXT NOT NULL UNIQUE,
    branch_name TEXT NOT NULL,
    city TEXT NOT NULL,
    region TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE erp_core.warehouses (
    warehouse_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL,
    branch_id INTEGER NOT NULL,
    warehouse_code TEXT NOT NULL UNIQUE,
    warehouse_name TEXT NOT NULL,
    city TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE erp_core.sales_channels (
    channel_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_code TEXT NOT NULL UNIQUE,
    channel_name TEXT NOT NULL,
    channel_type TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE erp_core.carriers (
    carrier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_code TEXT NOT NULL UNIQUE,
    carrier_name TEXT NOT NULL,
    service_level TEXT NOT NULL CHECK (service_level IN ('standard', 'express', 'same_day', 'b2b_freight')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE erp_core.customer_segments (
    segment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_code TEXT NOT NULL UNIQUE,
    segment_name TEXT NOT NULL,
    description TEXT
);

CREATE TABLE erp_core.customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id INTEGER NOT NULL,
    customer_code TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    customer_type TEXT NOT NULL CHECK (customer_type IN ('individual', 'business')),
    city TEXT NOT NULL,
    region TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE erp_core.product_categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_category_id INTEGER,
    category_code TEXT NOT NULL UNIQUE,
    category_name TEXT NOT NULL,
    level INTEGER NOT NULL CHECK (level > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE erp_core.products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL,
    sku TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    brand TEXT NOT NULL,
    unit_of_measure TEXT NOT NULL,
    standard_cost NUMERIC(18, 2) NOT NULL CHECK (standard_cost >= 0),
    list_price NUMERIC(18, 2) NOT NULL CHECK (list_price >= standard_cost),
    shelf_life_days INTEGER CHECK (shelf_life_days IS NULL OR shelf_life_days > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE erp_sales.price_lists (
    price_list_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    channel_id INTEGER NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    unit_price NUMERIC(18, 2) NOT NULL CHECK (unit_price >= 0),
    currency TEXT NOT NULL DEFAULT 'VND',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (valid_to >= valid_from),
    UNIQUE (product_id, channel_id, valid_from)
);

CREATE TABLE erp_sales.promotions (
    promotion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_code TEXT NOT NULL UNIQUE,
    promotion_name TEXT NOT NULL,
    channel_id INTEGER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    discount_type TEXT NOT NULL CHECK (discount_type IN ('percent', 'fixed_amount')),
    discount_value NUMERIC(18, 2) NOT NULL CHECK (discount_value >= 0),
    budget_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (budget_amount >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (end_date >= start_date)
);

CREATE TABLE erp_inventory.stock_balances (
    warehouse_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    on_hand_qty NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (on_hand_qty >= 0),
    reserved_qty NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (reserved_qty >= 0),
    reorder_point NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (reorder_point >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (warehouse_id, product_id),
    CHECK (reserved_qty <= on_hand_qty)
);

CREATE TABLE erp_inventory.stock_lots (
    lot_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    warehouse_id INTEGER NOT NULL,
    lot_number TEXT NOT NULL UNIQUE,
    manufacturing_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    quantity_on_hand NUMERIC(18, 3) NOT NULL CHECK (quantity_on_hand >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (expiration_date > manufacturing_date)
);

CREATE TABLE erp_sales.sales_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id INTEGER NOT NULL,
    branch_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    channel_id INTEGER NOT NULL,
    order_number TEXT NOT NULL UNIQUE,
    order_date DATE NOT NULL,
    order_status TEXT NOT NULL DEFAULT 'draft'
        CHECK (order_status IN ('draft', 'confirmed', 'fulfilled', 'invoiced', 'paid', 'cancelled')),
    currency TEXT NOT NULL DEFAULT 'VND',
    gross_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (gross_amount >= 0),
    discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    net_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (net_amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (discount_amount <= gross_amount),
    CHECK (net_amount = gross_amount - discount_amount)
);

CREATE TABLE erp_sales.sales_order_lines (
    order_line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    warehouse_id INTEGER NOT NULL,
    promotion_id INTEGER,
    quantity NUMERIC(18, 3) NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(18, 2) NOT NULL CHECK (unit_price >= 0),
    discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    gross_amount NUMERIC(18, 2) NOT NULL CHECK (gross_amount >= 0),
    net_amount NUMERIC(18, 2) NOT NULL CHECK (net_amount >= 0),
    estimated_cost NUMERIC(18, 2) NOT NULL CHECK (estimated_cost >= 0),
    CHECK (discount_amount <= gross_amount),
    CHECK (net_amount = gross_amount - discount_amount)
);

CREATE TABLE erp_logistics.shipments (
    shipment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    warehouse_id INTEGER NOT NULL,
    carrier_id INTEGER NOT NULL,
    shipment_number TEXT NOT NULL UNIQUE,
    planned_ship_date DATE NOT NULL,
    actual_ship_date DATE,
    planned_delivery_date DATE NOT NULL,
    actual_delivery_date DATE,
    shipment_status TEXT NOT NULL DEFAULT 'planned'
        CHECK (shipment_status IN ('planned', 'in_transit', 'delivered', 'failed', 'returned', 'cancelled')),
    shipping_fee NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (shipping_fee >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (planned_delivery_date >= planned_ship_date),
    CHECK (actual_ship_date IS NULL OR actual_ship_date >= planned_ship_date),
    CHECK (actual_delivery_date IS NULL OR actual_delivery_date >= planned_ship_date)
);

CREATE TABLE erp_logistics.delivery_attempts (
    delivery_attempt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id INTEGER NOT NULL,
    attempt_number INTEGER NOT NULL CHECK (attempt_number > 0),
    attempt_date DATE NOT NULL,
    attempt_status TEXT NOT NULL CHECK (attempt_status IN ('delivered', 'failed', 'rescheduled', 'returned')),
    failure_reason TEXT,
    cod_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (cod_amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shipment_id, attempt_number),
    CHECK (
        (attempt_status IN ('failed', 'returned') AND failure_reason IS NOT NULL)
        OR (attempt_status IN ('delivered', 'rescheduled'))
    )
);

CREATE TABLE erp_inventory.stock_moves (
    stock_move_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    order_line_id INTEGER,
    move_type TEXT NOT NULL CHECK (move_type IN ('purchase_receipt', 'sale_reservation', 'sale_delivery', 'return_receipt', 'adjustment')),
    move_date DATE NOT NULL,
    quantity NUMERIC(18, 3) NOT NULL CHECK (quantity <> 0),
    unit_cost NUMERIC(18, 2) NOT NULL CHECK (unit_cost >= 0),
    move_value NUMERIC(18, 2) NOT NULL,
    reference_number TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE erp_finance.invoices (
    invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    invoice_number TEXT NOT NULL UNIQUE,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    invoice_status TEXT NOT NULL DEFAULT 'open'
        CHECK (invoice_status IN ('open', 'partial', 'paid', 'cancelled')),
    gross_amount NUMERIC(18, 2) NOT NULL CHECK (gross_amount >= 0),
    tax_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    discount_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    net_amount NUMERIC(18, 2) NOT NULL CHECK (net_amount >= 0),
    amount_paid NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (due_date >= invoice_date),
    CHECK (amount_paid <= net_amount)
);

CREATE TABLE erp_finance.invoice_lines (
    invoice_line_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    order_line_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity NUMERIC(18, 3) NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(18, 2) NOT NULL CHECK (unit_price >= 0),
    gross_amount NUMERIC(18, 2) NOT NULL CHECK (gross_amount >= 0),
    tax_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    net_amount NUMERIC(18, 2) NOT NULL CHECK (net_amount >= 0)
);

CREATE TABLE erp_finance.payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    payment_date DATE NOT NULL,
    payment_method TEXT NOT NULL CHECK (payment_method IN ('bank_transfer', 'cash', 'card', 'e_wallet')),
    payment_status TEXT NOT NULL DEFAULT 'paid' CHECK (payment_status IN ('paid', 'reversed')),
    amount_paid NUMERIC(18, 2) NOT NULL CHECK (amount_paid > 0),
    transaction_reference TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE erp_sales.returns (
    return_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    order_line_id INTEGER NOT NULL,
    customer_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    return_date DATE NOT NULL,
    return_reason TEXT NOT NULL,
    quantity NUMERIC(18, 3) NOT NULL CHECK (quantity > 0),
    refund_amount NUMERIC(18, 2) NOT NULL CHECK (refund_amount >= 0),
    return_status TEXT NOT NULL DEFAULT 'approved'
        CHECK (return_status IN ('approved', 'refunded', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Foreign keys are intentionally disabled for the current mock-source phase.
-- Keep this block as the canonical relationship map. Uncomment it later when
-- the source database should enforce referential integrity directly.
--
-- ALTER TABLE erp_core.branches
--     ADD CONSTRAINT fk_branches_company
--     FOREIGN KEY (company_id) REFERENCES erp_core.companies(company_id);
--
-- ALTER TABLE erp_core.warehouses
--     ADD CONSTRAINT fk_warehouses_company
--     FOREIGN KEY (company_id) REFERENCES erp_core.companies(company_id);
--
-- ALTER TABLE erp_core.warehouses
--     ADD CONSTRAINT fk_warehouses_branch
--     FOREIGN KEY (branch_id) REFERENCES erp_core.branches(branch_id);
--
-- ALTER TABLE erp_core.customers
--     ADD CONSTRAINT fk_customers_segment
--     FOREIGN KEY (segment_id) REFERENCES erp_core.customer_segments(segment_id);
--
-- ALTER TABLE erp_core.product_categories
--     ADD CONSTRAINT fk_product_categories_parent
--     FOREIGN KEY (parent_category_id) REFERENCES erp_core.product_categories(category_id);
--
-- ALTER TABLE erp_core.products
--     ADD CONSTRAINT fk_products_category
--     FOREIGN KEY (category_id) REFERENCES erp_core.product_categories(category_id);
--
-- ALTER TABLE erp_sales.price_lists
--     ADD CONSTRAINT fk_price_lists_product
--     FOREIGN KEY (product_id) REFERENCES erp_core.products(product_id);
--
-- ALTER TABLE erp_sales.price_lists
--     ADD CONSTRAINT fk_price_lists_channel
--     FOREIGN KEY (channel_id) REFERENCES erp_core.sales_channels(channel_id);
--
-- ALTER TABLE erp_sales.promotions
--     ADD CONSTRAINT fk_promotions_channel
--     FOREIGN KEY (channel_id) REFERENCES erp_core.sales_channels(channel_id);
--
-- ALTER TABLE erp_inventory.stock_balances
--     ADD CONSTRAINT fk_stock_balances_warehouse
--     FOREIGN KEY (warehouse_id) REFERENCES erp_core.warehouses(warehouse_id);
--
-- ALTER TABLE erp_inventory.stock_balances
--     ADD CONSTRAINT fk_stock_balances_product
--     FOREIGN KEY (product_id) REFERENCES erp_core.products(product_id);
--
-- ALTER TABLE erp_inventory.stock_lots
--     ADD CONSTRAINT fk_stock_lots_product
--     FOREIGN KEY (product_id) REFERENCES erp_core.products(product_id);
--
-- ALTER TABLE erp_inventory.stock_lots
--     ADD CONSTRAINT fk_stock_lots_warehouse
--     FOREIGN KEY (warehouse_id) REFERENCES erp_core.warehouses(warehouse_id);
--
-- ALTER TABLE erp_sales.sales_orders
--     ADD CONSTRAINT fk_sales_orders_company
--     FOREIGN KEY (company_id) REFERENCES erp_core.companies(company_id);
--
-- ALTER TABLE erp_sales.sales_orders
--     ADD CONSTRAINT fk_sales_orders_branch
--     FOREIGN KEY (branch_id) REFERENCES erp_core.branches(branch_id);
--
-- ALTER TABLE erp_sales.sales_orders
--     ADD CONSTRAINT fk_sales_orders_customer
--     FOREIGN KEY (customer_id) REFERENCES erp_core.customers(customer_id);
--
-- ALTER TABLE erp_sales.sales_orders
--     ADD CONSTRAINT fk_sales_orders_channel
--     FOREIGN KEY (channel_id) REFERENCES erp_core.sales_channels(channel_id);
--
-- ALTER TABLE erp_sales.sales_order_lines
--     ADD CONSTRAINT fk_sales_order_lines_order
--     FOREIGN KEY (order_id) REFERENCES erp_sales.sales_orders(order_id) ON DELETE CASCADE;
--
-- ALTER TABLE erp_sales.sales_order_lines
--     ADD CONSTRAINT fk_sales_order_lines_product
--     FOREIGN KEY (product_id) REFERENCES erp_core.products(product_id);
--
-- ALTER TABLE erp_sales.sales_order_lines
--     ADD CONSTRAINT fk_sales_order_lines_warehouse
--     FOREIGN KEY (warehouse_id) REFERENCES erp_core.warehouses(warehouse_id);
--
-- ALTER TABLE erp_sales.sales_order_lines
--     ADD CONSTRAINT fk_sales_order_lines_promotion
--     FOREIGN KEY (promotion_id) REFERENCES erp_sales.promotions(promotion_id);
--
-- ALTER TABLE erp_logistics.shipments
--     ADD CONSTRAINT fk_shipments_order
--     FOREIGN KEY (order_id) REFERENCES erp_sales.sales_orders(order_id);
--
-- ALTER TABLE erp_logistics.shipments
--     ADD CONSTRAINT fk_shipments_warehouse
--     FOREIGN KEY (warehouse_id) REFERENCES erp_core.warehouses(warehouse_id);
--
-- ALTER TABLE erp_logistics.shipments
--     ADD CONSTRAINT fk_shipments_carrier
--     FOREIGN KEY (carrier_id) REFERENCES erp_core.carriers(carrier_id);
--
-- ALTER TABLE erp_logistics.delivery_attempts
--     ADD CONSTRAINT fk_delivery_attempts_shipment
--     FOREIGN KEY (shipment_id) REFERENCES erp_logistics.shipments(shipment_id);
--
-- ALTER TABLE erp_inventory.stock_moves
--     ADD CONSTRAINT fk_stock_moves_warehouse
--     FOREIGN KEY (warehouse_id) REFERENCES erp_core.warehouses(warehouse_id);
--
-- ALTER TABLE erp_inventory.stock_moves
--     ADD CONSTRAINT fk_stock_moves_product
--     FOREIGN KEY (product_id) REFERENCES erp_core.products(product_id);
--
-- ALTER TABLE erp_inventory.stock_moves
--     ADD CONSTRAINT fk_stock_moves_order_line
--     FOREIGN KEY (order_line_id) REFERENCES erp_sales.sales_order_lines(order_line_id);
--
-- ALTER TABLE erp_finance.invoices
--     ADD CONSTRAINT fk_invoices_order
--     FOREIGN KEY (order_id) REFERENCES erp_sales.sales_orders(order_id);
--
-- ALTER TABLE erp_finance.invoices
--     ADD CONSTRAINT fk_invoices_customer
--     FOREIGN KEY (customer_id) REFERENCES erp_core.customers(customer_id);
--
-- ALTER TABLE erp_finance.invoice_lines
--     ADD CONSTRAINT fk_invoice_lines_invoice
--     FOREIGN KEY (invoice_id) REFERENCES erp_finance.invoices(invoice_id) ON DELETE CASCADE;
--
-- ALTER TABLE erp_finance.invoice_lines
--     ADD CONSTRAINT fk_invoice_lines_order_line
--     FOREIGN KEY (order_line_id) REFERENCES erp_sales.sales_order_lines(order_line_id);
--
-- ALTER TABLE erp_finance.invoice_lines
--     ADD CONSTRAINT fk_invoice_lines_product
--     FOREIGN KEY (product_id) REFERENCES erp_core.products(product_id);
--
-- ALTER TABLE erp_finance.payments
--     ADD CONSTRAINT fk_payments_invoice
--     FOREIGN KEY (invoice_id) REFERENCES erp_finance.invoices(invoice_id);
--
-- ALTER TABLE erp_finance.payments
--     ADD CONSTRAINT fk_payments_customer
--     FOREIGN KEY (customer_id) REFERENCES erp_core.customers(customer_id);
--
-- ALTER TABLE erp_sales.returns
--     ADD CONSTRAINT fk_returns_order
--     FOREIGN KEY (order_id) REFERENCES erp_sales.sales_orders(order_id);
--
-- ALTER TABLE erp_sales.returns
--     ADD CONSTRAINT fk_returns_order_line
--     FOREIGN KEY (order_line_id) REFERENCES erp_sales.sales_order_lines(order_line_id);
--
-- ALTER TABLE erp_sales.returns
--     ADD CONSTRAINT fk_returns_customer
--     FOREIGN KEY (customer_id) REFERENCES erp_core.customers(customer_id);
--
-- ALTER TABLE erp_sales.returns
--     ADD CONSTRAINT fk_returns_product
--     FOREIGN KEY (product_id) REFERENCES erp_core.products(product_id);
