-- Generated by data_source.mock_data_factory.
-- Scenario set: omnichannel_d2c_fmcg

DO $$
DECLARE
    v_order_id INTEGER;
    v_invoice_id INTEGER;
BEGIN
    -- Scenario: vip_customer_website_order_partial_payment
    v_order_id := erp_sales.create_sales_order(1, 2, 1, DATE '2026-08-01');
    PERFORM erp_sales.add_sales_order_line(v_order_id, 1, 1, 12, NULL, 0, 1);
    PERFORM erp_sales.add_sales_order_line(v_order_id, 4, 1, 5, NULL, 0, NULL);
    PERFORM erp_sales.confirm_order(v_order_id);
    PERFORM erp_sales.fulfill_order(v_order_id, DATE '2026-08-02', 2);
    v_invoice_id := erp_finance.create_invoice_from_order(v_order_id, DATE '2026-08-02', 15);
    PERFORM erp_finance.record_payment(v_invoice_id, 100000, 'e_wallet', DATE '2026-08-03');

    -- Scenario: b2b_bulk_order_partial_payment
    v_order_id := erp_sales.create_sales_order(3, 4, 2, DATE '2026-08-02');
    PERFORM erp_sales.add_sales_order_line(v_order_id, 2, 2, 50, 10000, 0, 3);
    PERFORM erp_sales.add_sales_order_line(v_order_id, 3, 2, 20, 20000, 20000, NULL);
    PERFORM erp_sales.confirm_order(v_order_id);
    PERFORM erp_sales.fulfill_order(v_order_id, DATE '2026-08-04', 5);
    v_invoice_id := erp_finance.create_invoice_from_order(v_order_id, DATE '2026-08-04', 30);
    PERFORM erp_finance.record_payment(v_invoice_id, 300000, 'bank_transfer', DATE '2026-08-05');

END;
$$;
